fpr/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

import views

urlpatterns = [
    url('^$', views.index, name='index'),
]

intranet/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from intranet import settings
import django.contrib.auth.views
from django.views.decorators.debug import sensitive_post_parameters
from intranet.views import accueil, surlogin, surlogout

from django.contrib import admin
admin.autodiscover()

if settings.CAS_ENABLED:
    from django_cas_ng.signals import cas_user_authenticated
    from intranet.login import post_cas_login
    cas_user_authenticated.connect(post_cas_login)
    from django_cas_ng.views import login, logout
    login_url = url(r'^login$', login, name="login")
    logout_url = url(r'^logout$', logout, name="logout")
else:
    login_view = django.contrib.auth.views.login
    login_view = sensitive_post_parameters('password')(login_view)
    login_url = url('^login', login_view, {'template_name': 'login.html'}, name="login")
    #login_url = url('^login', protect(django.contrib.auth.views.login), {'template_name': 'login.html'}, name="login")
    logout_url = url('^logout', django.contrib.auth.views.logout_then_login, name ="logout")

urlpatterns = [
    # Les pages existantes
    url('^$', accueil, name='index'),
    url('^surlogin$', surlogin, name='surlogin'),
    url('^surlogout$', surlogout, name='surlogout'),
    # Pages de login
    login_url,
    logout_url,
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

for app in settings.INTRANET_APPS:
    app_name = app["name"]
    module = app.get('module', app_name)
    urlpatterns += [url('^%s/' % app_name, include('%s.urls' % module,
                                                       namespace = app_name,
                                                       app_name = app_name))]

# Pour une raison inconnue, ces valeurs par défaut ne sont pas définies ...
handler404='django.views.defaults.page_not_found'
handler403='django.views.defaults.permission_denied'
handler500='django.views.defaults.server_error'

voip/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

import views

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^edit/$', views.edit, name="edit"),
    url('^delete/$', views.delete, name="delete"),
    url('^book/$', views.book, name="book"),
    url('^book/download$', views.book, {'download': True}, name="book_download",),
    url('^history/$', views.history, name="history"),
    url('^history/(?P<page>[0-9]+)$', views.history),
]

voip/models.py
# -*- coding: utf-8 -*-

from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

from intranet import settings, conn_pool
class asterisk_reload_conf_debug:
    @classmethod
    def reload_config(self, fname):
        pass

# TODO weird stuff here
try:
    from sip import asterisk_reload_conf
except ImportError:
    if not settings.DEBUG:
        raise
    asterisk_reload_conf = asterisk_reload_conf_debug

from django.db import models
from django.contrib.auth.models import User
import hashlib
import os

# Description de la configuration générée pour asterisk
# TODO eurk
asterisk_conf = {
    'modules':{
        'sip':{
            'reload_fields':["caller_id","password"],
            'gen_conf':lambda _:Profile.asterisk_config, # pour pouvoir appeler Profile paresseusement
            'conf_file':'sip_accounts',
        },
        'voicemail':{
            'reload_fields':["voicemail_password"],
            'gen_conf':lambda _:Profile.asterisk_voicemail_config,
            'conf_file':'sip_accounts_voicemail',
        },
        'dialplan':{
            'reload_fields':["num"],
            'gen_conf':lambda _:Profile.asterisk_alias_config,
            'conf_file':'sip_accounts_alias',
        },
   },
   'conf_path':'/usr/scripts/var/sip/'
}


class Profile(models.Model):
    """ Profil d'utilisateur Voip """

    class Meta:
        verbose_name = _(u'Profil SIP')
        verbose_name_plural = _(u'Profils SIP')

    CALLER_IDS = [
        ('full_name', _(u'Nom complet')),
        ('number', _(u'Numéro de Téléphone')),
        ('both', _(u'Nom et numéro de téléphone')),
    ]

    """ Propriétaire du profil. Devrait être un compte Cr@ns """
    user = models.OneToOneField(User, primary_key=True)

    """ Mot de passe. Hashé en md5 avec un sel
        (md5($num_asterisk:asterisk:$pass)) """
    password = models.CharField(_(u"Mot de passe"), max_length=32, null=False, blank=False)

    """ Autoriser ou non la publication dans l'annuaire """
    published = models.BooleanField(_(u"Publication dans l'annuaire"), help_text=u"Affichage du numéro et du nom dans l'annuaire du Crans", default=False)

    """ Choix du format pour l'identification de l'appelant """
    caller_id = models.CharField(_(u"Affichage de l'appelant"), max_length=9, choices=CALLER_IDS, help_text=u"Nom à afficher lors d'un appel")

    """ Numéro de téléphone, on utilise un varchar afin de pouvoir placer des 0
        initiaux et des éventuels #"""
    num = models.CharField(_(u"Numéro de téléphone"), max_length=10, null=False, blank=False)
    voicemail_password = models.CharField(_(u"Mot de passe boîte vocale"), max_length=6, null=False, blank=False)


    def what_to_reload(self):
        """ Defini les modules asterisk dont il faut régénérer la configuration """
        def has_changed(self, field):
            if not self.pk:
                return True
            try:
                old_value = self.__class__._default_manager.\
                         filter(pk=self.pk).values(field).get()[field]
            except self.DoesNotExist:
                return True
            return not getattr(self, field) == old_value

        modules={}
        for module in asterisk_conf['modules'].keys():
            modules[module]=reduce( # List.fold_left
                lambda x,y: x or has_changed(self,y),
                asterisk_conf['modules'][module]['reload_fields'],
                False
            )
        return modules

    def reload_what_it_is_to_reload(self,modules):
        """ Écrit la configuration des modules asterisk à recharger, puis les recharge """
        def writeconf(gen_conf_module,path):
            conf=""
            for profile in Profile.objects.order_by('user__username').all():
                conf+=gen_conf_module(profile).encode('utf-8') + '\n'
            tmppath = path + '.new'
            if not settings.DEBUG:
                with open(tmppath,'w') as fout:
                    fout.write(conf)
                os.rename(tmppath, path)
        for module in asterisk_conf['modules'].keys():
            if modules[module]:
                writeconf(
                    asterisk_conf['modules'][module]['gen_conf'](''),
                    asterisk_conf['conf_path'] + asterisk_conf['modules'][module][ 'conf_file']
                )
        
        if reduce(lambda x,y: x or y, modules.values(), False):
            asterisk_reload_conf.reload_config('all')
        else:
            for module in asterisk_conf['modules'].keys(): 
                if modules[module]:
                    asterisk_reload_conf.reload_config(module)

    def delete(self):
        ret=super(Profile,self).delete()
        self.reload_what_it_is_to_reload(self.what_to_reload())
        return ret

    def save(self):
        to_reload=self.what_to_reload()
        ret=super(Profile,self).save()
        self.reload_what_it_is_to_reload(to_reload)
        return ret

    def set_user(self, new_user):
        """ Défini l'utilisateur propriétaire du profil. Cette fonction calcule
        également le numéro de téléphone correspondant, à partir de la base LDAP.
        IMPORTANT: changer d'utilisateur (donc de numéro de téléphone) casse
        le mot de passe, qui devra être redéfini."""
        self.user = new_user
        try:
            aid = conn_pool.get_user(new_user)['aid'][0].value
            sip_ext = '1%04d' % int(str(aid)[:4])
        except KeyError:
            if not settings.DEBUG:
                raise Exception("Not allowed") # FIXME ?
            sip_ext = '9%04d' % int(str(new_user.pk)[:4])
        self.num = sip_ext

    def set_password(self, new_pass):
        """ Définition du mot de passe.
        IMPORTANT: le mot de passe est stocké hashé dans la base de donnée.
        Il faut donc avoir préalablement défini le numéro de téléphone (et
        donc l'utilisateur) avant d'appeler cette fonction.
        """
        if self.num == '':
            raise Exception('Set user/num first')
        self.password = hashlib.md5("%s:asterisk:%s" % (self.num, new_pass)).hexdigest()

    def __unicode__(self):
        #return _(u"Profil de %s (dont le numéro est %s)") % (self.user.username, self.num)
        return _(u"Profil de %(login)s (dont le numéro est %(numero)s)") % \
           {
              'login': self.user.username,
              'numero': self.num
           }

    def asterisk_alias_config(self):
        """Génération de la ligne de conf asterisk mappant login à son numéro correspondant"""
        return "exten => %(login)s,1,Goto(%(num)s,1)" % {'num':self.num,'login':self.user.username.split('@')[0]}

    def asterisk_voicemail_config(self):
        """ Génération de la ligne de conf asterisk activant la boîte vocale"""
        return u"%(num)s => %(mail_pass)s,%(full_name)s,%(mail)s,,attach=%(attach)s|delete=%(delete)s" % {
       'num':self.num,'mail_pass':self.voicemail_password,'full_name':self.user.get_full_name(),
       'mail':self.user.username,'attach':'yes','delete':'no'}

    def asterisk_config(self):
        """ Génération du paragraphe de conf asterisk definissant l'utilisateur"""
        return u""";%(uid)s
[%(num)s](default-crans)
username=%(num)s
callerid="%(callerid)s"
md5secret=%(passwd)s
mailbox=%(num)s@666
""" % {
 'callerid': self.get_caller_id(),
 'num': self.num,
 'passwd': self.password,
 'uid': self.user.username,
}


    def get_category(self):
        """ Renvoie la catégorie du profil, dans l'annuaire """
        return "Cr@ns"

    def get_caller_id(self):
        """ Calcule le texte descriptif de l'appelant """
        if self.caller_id == 'full_name':
            return self.user.get_full_name()
        elif self.caller_id == 'number':
            return self.num
        else: # Both
            return self.user.get_full_name() + u' <' + self.num + u'>'

class Call(models.Model):
    """ Un appel archivé.
    Automatiquement rempli par asterisk (et les scripts maisons de Nit)
    """

    class Meta:
        """La table s'appelle history, on définit ici plutôt un nom pour un objet"""
        db_table = 'voip_history'
        verbose_name = _(u'Appel archivé')
        verbose_name_plural = _(u'Appels archivés')

    uniq_id = models.CharField(_(u"Identifiant de l'appel"), max_length=80, primary_key=True)
    src = models.CharField(_(u"Numéro appelant"), max_length=80)
    dst = models.CharField(_(u"Numéro appelant"), max_length=80)

    """ Une durée égale à NULL correspond à un appel en cours (sauf si plantage) """
    duration = models.IntegerField(_(u"Durée de l'appel"), null=True, blank=True)
    date = models.DateField(_(u"Date d'initiation de l'appel"))

    def __unicode__(self):
        o = u"%s -> %s @ %s" % (self.src, self.dst, self.date)
        if self.duration:
            o += " (%ds)" % self.duration
        return o

voip/views.py
# -*- encoding: utf-8 -*-

import django.shortcuts
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.views.decorators.debug import sensitive_post_parameters

from models import Profile, Call
from forms import ProfileForm
from django.core.urlresolvers import reverse

from django.views.generic.edit import DeleteView
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q

import datetime

@login_required
def index(request):
    try:
        profile = Profile.objects.filter(user__exact=request.user)[0]
    except IndexError:
        return django.shortcuts.render(request, "voip/noaccount.html")
    
    return django.shortcuts.render(request, "voip/view.html",
        {'profile': profile,})

@login_required
@sensitive_post_parameters('voicemail_password', 'pass_change2', 'pass_change1')
def edit(request):
    try:
        profile = Profile.objects.filter(user__exact=request.user)[0]
    except IndexError:
        profile = None
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile, user=request.user)
        if form.is_valid():
            profile = form.save()
            return django.shortcuts.redirect('voip:index')
    else:
        form = ProfileForm(instance=profile)
    return django.shortcuts.render(request, "voip/edit.html", {'form': form})

@login_required
def delete(request):
    obj = get_object_or_404(Profile, user__exact=request.user)
    if request.method == 'POST':
        obj.delete()
        return django.shortcuts.redirect('apps.accueil.views.view')
    return django.shortcuts.render(request, "confirm.html", {
        'confirm_title': _(u'Suppression du compte SIP'),
        'confirm_message': _(u'Êtes-vous sûr de vouloir effacer votre compte téléphonique ?'),
        'confirm_cancel_url': reverse('voip:index'),
    })

@login_required
def book(request, download=False):
    data = {'profiles': Profile.objects.filter(published__exact=True).order_by('num')}
    if not download:
        return django.shortcuts.render(request, "voip/book.html", data)

    response = django.shortcuts.render(request, "voip/book.vcf", data,
        content_type='text/x-vcard')
    date = datetime.datetime.now()
    response['Content-Disposition'] = 'attachment; filename="CransBook_%d_%d_%d.vcf"' % (date.day, date.month, date.year)
    return response

@login_required
def history(request, page=None):
    """ Affiche un historique des appels, paginé """
    num = get_object_or_404(Profile, user__exact=request.user).num

    hist_list = Call.objects.filter(
        Q(dst__exact=num)|Q(src__exact=num)
        ).order_by('-date')

    paginator = Paginator(hist_list, 25)

    try:
        hist = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        hist = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        hist = paginator.page(paginator.num_pages)

    return django.shortcuts.render(request, 'voip/history.html', {
        "history": hist,
    })

voip/templates/voip/base.html
{% extends "template.html" %}
{% load i18n %}
{% block title%}Gestion des la VoIP{% endblock %}
{% block h1%} Gestion de la VoIP {% endblock %}
{% block head %}<link rel="stylesheet" type="text/css" href="/static/css/machines.css" />{% endblock %}
{% block content %}
<div id="globalDiv">
  {%block actions%}
  <div id="menu_actions">
    <h1>{% trans "ACTIONS" %}</h1>
    {%block actions_list %}{% endblock %}
  </div>
  {% endblock %}
  <div id="machines_border">
<div id="listeMachines_frame">
<div id="machine_pane">
  {% block machines %}{% endblock %}
<div style="clear:both;">
  </div>
</div>
</div>
</div>
{% endblock %}

voip/templates/voip/book.html
{% extends "template.html" %}
{% load i18n %}
{% block content %}
<h2>{% trans "Annuaire" %}</h2>
<table>
  <tr>
    <th>{% trans "Nom" %}</th>
    <th>{% trans "Prénom" %}</th>
    <th>{% trans "Numéro" %}</th>
  </tr>
{% for profile in profiles %}
  <tr>
    <td>{{ profile.user.last_name }}</td>
    <td>{{ profile.user.first_name }}</td>
    <td>{{ profile.num }}</td>
  </tr>
{% endfor %}
</table>
<a href="{% url 'voip:index' %}"><button class="button-cancel">{% trans "Retour aux paramètres" %}</button></a>
<a href="{% url 'voip:book_download' %}"><button>{% trans "Télécharger (vcf)" %}</button></a>
{% endblock %}

voip/templates/voip/edit.html
{% extends "template.html" %}
{% load i18n %}
{% block content %}
<form method="post" class="form-full-width">{% csrf_token %}
<div class="row">
  <div class="six columns">
    {{ form.published.label_tag }}
    {{ form.published }}
    {{ form.published.help_text }}
    {{ form.published.errors }}
  </div>
  <div class="six columns">
    {{ form.caller_id.label_tag }}
    {{ form.caller_id }}
    {{ form.caller_id.help_text }}
    {{ form.caller_id.errors }}
  </div>
</div>
<div class="row">
  <div class="six columns">
    {{ form.voicemail_password.label_tag }}
    {{ form.voicemail_password }}
    {{ form.voicemail_password.help_text }}
    {{ form.voicemail_password.errors }}
  </div>
</div>
<div class="row">
  <div class="six columns">
    {{ form.pass_change1.label_tag }}
    {{ form.pass_change1 }}
    {{ form.pass_change1.help_text }}
    {{ form.pass_change1.errors }}
  </div>
  <div class="six columns">
    {{ form.pass_change2.label_tag }}
    {{ form.pass_change2 }}
    {{ form.pass_change2.help_text }}
    {{ form.pass_change2.errors }}
  </div>
</div>
<footer>
  <a href="{% url 'voip:index' %}" class="button-cancel">{% trans "Retour aux paramètres" %}</a>
  <input type="submit" value="{% trans "Enregistrer les changements" %}" />
</footer>
</form>

{% endblock %}

voip/templates/voip/history.html
{% extends "template.html" %}
{% load i18n %}
{% block content %}
<h2>{% trans "Historique des appels" %}</h2>
<table>
  <tr>
    <th>{% trans "Source" %}</th>
    <th>{% trans "Destination" %}</th>
    <th>{% trans "Date" %}</th>
    <th>{% trans "Durée (s)" %}</th>
  </tr>
{% for call in history %}
  <tr>
    <td>{{ call.src }}</td>
    <td>{{ call.dst }}</td>
    <td>{{ call.date }}</td>
    <td>{{ call.duration }}</td>
  </tr>
{% endfor %}
</table>
<div class="pagination">
    <span class="step-links">
        {% if history.has_previous %}
            <a href="{{ history.previous_page_number }}">{% trans "Précédent" %}</a>
        {% endif %}

        <span class="current">
            {% blocktrans with history.number as page and history.paginator.num_pages as total %}
            Page {{ page }} sur {{ total }}.
            {% endblocktrans %}
        </span>

        {% if history.has_next %}
            <a href="{{ history.next_page_number }}">{% trans "Suivant" %}</a>
        {% endif %}
    </span>
</div>
<a href="{% url 'voip:index' %}"><button class="button-cancel">
    {% trans "Retour aux paramètres" %}
</button></a>
{% endblock content %}

voip/templates/voip/noaccount.html
{% extends "template.html" %}
{% load i18n %}
{% block content %}
{% blocktrans %}
Vous n'avez pas encore activé votre compte SIP.
{% endblocktrans %}
<a href="{% url 'voip:edit' %}">{% trans "Créer votre compte" %}</a>
{% endblock %}

voip/templates/voip/view.html
{% extends "template.html" %}
{% load i18n %}
{% block content %}
<h2>{% trans "Vos paramètres de connexion" %}</h2>
<div class="row">
  <div class="four columns">
    <label>{% trans "Serveur :" %}</label>
    sip.crans.org
  </div>
  <div class="four columns">
    <label>{% trans "Nom d'utilisateur :" %}</label>
    {{ profile.num }}
  </div>
  <div class="four columns">
    <label>{% trans "Mot de passe :" %}</label>
    *******
  </div>
</div>
<div class="row">
  <div class="four columns">
    <label>{% trans "Publication dans l'annuaire :" %}</label>
    {{ profile.published|yesno:_("Activée,Désactivée") }}
  </div>
  <div class="four columns">
    <label>{% trans "Présentation de l'appelant :" %}</label>
    {{ profile.get_caller_id_display }} ({{ profile.get_caller_id }})
  </div>
</div>
<div class="row">
  <div class="four columns">
    <label>{% trans "Numéro de la messagerie :" %}</label>
    666
  </div>
  <div class="four columns">
    <label>{% trans "Mot de passe de messagerie :" %}</label>
    {{ profile.voicemail_password }}
  </div>
</div>
<a href="{% url 'voip:edit' %}"><button>{% trans "Éditer mes informations" %}</button></a>
<a href="{% url 'voip:history' %}"><button>{% trans "Historique" %}</button></a>
<a href="{% url 'voip:book' %}"><button>{% trans "Annuaire" %}</button></a>
<a href="{% url 'voip:delete' %}"><button class="button-del">{% trans "Effacer mon compte" %}</button></a>

{% endblock %}